<a href="https://colab.research.google.com/github/arbi11/YCBS-272/blob/master/Lec_2_solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Import the necessary libraries

In [0]:
import numpy as np

## 1.1 Creating a numpy array

In [0]:
data = np.random.rand(2, 4)

the array can be printed with just mentioning the variable name

In [3]:
data

array([[0.852263  , 0.38289844, 0.34887533, 0.08102405],
       [0.74691592, 0.05304594, 0.43137898, 0.43207251]])

## Q1.1 Create a variable with size [3, 6]

In [0]:
data = np.random.rand(3, 6)

In [5]:
data

array([[0.21845961, 0.0360743 , 0.88404217, 0.76070453, 0.92936566,
        0.91772636],
       [0.75706455, 0.05530078, 0.55762135, 0.70372948, 0.25520796,
        0.43015301],
       [0.06038419, 0.57908929, 0.33515397, 0.03069733, 0.0413684 ,
        0.84951881]])

In [6]:
data.shape

(3, 6)

In [7]:
data.dtype

dtype('float64')

## 1.2 Creating a numpy array from sampling via normal distribution
creating an array with random numbers from normal distribution

N(mu, sd)


numpy samples from N(mu, variance) of N(0, 1)

In [0]:
data = np.random.randn(2, 4)
data

array([[ 0.50342014,  1.28165121,  1.20886991,  0.22903815],
       [ 0.22199126,  0.95831356, -1.79270578,  0.6123828 ]])

## Q 1.2. Create a variable with normal data size [2, 4] with mu = 5 and sd = 2
variance = ?

In [0]:
data_new = 2*np.random.randn(2, 4) + 5

In [9]:
data_new

array([[5.4976978 , 4.94513138, 2.8187206 , 7.19245314],
       [4.01373963, 3.01257435, 4.71145203, 2.06134307]])

## 1.3 Data shape

In [10]:
data.shape


(3, 6)

## 1.4 Data type

In [11]:
data.dtype 


dtype('float64')

In [0]:
arr = np.array([1, 2, 3, 4, 5])

In [13]:
arr.dtype

dtype('int64')

In [0]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1], dtype= np.float32)

In [15]:
arr.dtype

dtype('float32')

### 1.4.1 integers were cast to floating point. If I cast some floating point numbers to be of integer dtype, the decimal part will be truncated

In [0]:
arr2 = arr.astype(np.int32)

In [17]:
arr2

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [0]:
arr3 = arr2.astype(float)

In [19]:
arr3

array([ 3., -1., -2.,  0., 12., 10.])

In [20]:
arr3.dtype

dtype('float64')

## 1.5 Perform mathematical operations on whole blocks of data

In [22]:
arr3*2

array([ 6., -2., -4.,  0., 24., 20.])

In [23]:
arr3+arr2

array([ 6., -2., -4.,  0., 24., 20.])

In [25]:
1/data

array([[ 4.57750519, 27.72056732,  1.13116776,  1.31457084,  1.07600274,
         1.08964942],
       [ 1.32089133, 18.08292857,  1.79333164,  1.42100058,  3.9183731 ,
         2.32475416],
       [16.56062665,  1.72684941,  2.9837033 , 32.57612166, 24.17303781,
         1.17713697]])

In [27]:
data.shape

(3, 6)

In [0]:
data.dtype

dtype('int64')

In [28]:
data

array([[0.21845961, 0.0360743 , 0.88404217, 0.76070453, 0.92936566,
        0.91772636],
       [0.75706455, 0.05530078, 0.55762135, 0.70372948, 0.25520796,
        0.43015301],
       [0.06038419, 0.57908929, 0.33515397, 0.03069733, 0.0413684 ,
        0.84951881]])

## Q 1.5. How to provide a copy of the data rather than just a view

In [0]:
data2 = data.copy()

integers were cast to floating point. If I cast some floating point numbers to be of integer dtype, the decimal part will be truncated

## 1.6 Indexing & Slicing - 1D

In [80]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

select the element at 6th index. Remember first index starts is at 0.

## Q. 1.6 Select the first element

In [31]:
data[0]

0

select from 5th to 7th element. Stop index not included.

In [32]:
data[5:8]	


array([5, 6, 7])

Indexing & assignment

In [34]:
data[5:8] = 6
data

array([0, 1, 2, 3, 4, 6, 6, 6, 8, 9])

In [35]:
data[:] = 0 
data

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## 1.8 Ndarray - Indexing & Slicing - Higher dimension


In [43]:
data_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
data_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

selects the 3rd row

In [37]:
data_2d[2] 			


array([7, 8, 9])

 select elements with <row, column> indexing format

In [38]:
data_2d[0][2]		


3

What will this do?

In [39]:
data_2d[0, 2] 		

3

Another way for indexing

Slicing: select range of elements


In [40]:
data_2d[:2] 		# slicing along axis 0 (row): select everything above row#3


array([[1, 2, 3],
       [4, 5, 6]])

In [81]:
data_2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [82]:
data_2d[1, :2]		# practice in colab


array([3, 4])

In [83]:
data_2d[:, -1]

array([2, 5, 8])

## 1.8 ndarray - Transposing & Swapping Axes

In [84]:
data = np.arange(15)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [86]:
data = np.arange(15).reshape((3, 5))  
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [87]:
data.shape 					# check in colab


(3, 5)

In [51]:
data.T 						# transpose of the original ndarray

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [53]:
data.T.shape

(5, 3)

For high dimension


In [99]:
data_3d = np.arange(24).reshape((2, 3, 4))  # accepts a tuple of axis
data_3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [100]:
data_3d.shape

(2, 3, 4)

In [101]:
data_3d_new = data_3d.transpose((1, 0, 2)).copy()
data_3d_new.shape

(3, 2, 4)

In [0]:
data_3d[0, 0] = 10

In [103]:
data_3d_new

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

In [104]:
data_3d

array([[[10, 10, 10, 10],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [89]:
data_3d.transpose((1, 0, 2)).shape


(3, 2, 4)

In [90]:
data_3d.shape

(2, 3, 4)

Q. Are you creating a copy or view?

Q. Check what .T will do on high dimensional data?

Q. Try data_3d.swapaxes(1,2)


In [79]:
data_3d.swapaxes(1,2).shape

(2, 4, 3)

In [65]:
data_3d.T.shape

(4, 3, 2)

## 1.9 ndarray - Statistical methods


In [105]:
data = np.random.randn(5, 4) 		# normally-distributed data  
data

array([[ 2.07811042,  0.68504652, -0.33140053,  0.21605969],
       [-0.97215561, -1.44723372, -1.52089982, -0.61042466],
       [-1.85910798, -1.11027599,  1.24481886,  0.51583856],
       [ 0.00810551, -0.05908333,  0.26003546, -1.22562135],
       [-0.86522315,  1.07915769, -0.25628432,  2.21537583]])

In [106]:
data.mean() 					


-0.09775809688251016

In [107]:
np.mean(data) 				


-0.09775809688251016

For high dimension data
data_2d = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])  
data_2d.mean(axis=1) 				# mean over the given axis  
data_2d.sum(0) 		

In [108]:
data_2d = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])  
data_2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [109]:
data_2d.mean(axis=1) 				# mean over the given axis  


array([1., 4., 7.])

In [73]:
data_2d.mean(axis=0) 				# mean over the given axis  


array([3., 4., 5.])

In [75]:
data_2d.mean(0)

array([3., 4., 5.])

In [74]:
data_2d.sum(0) 		

array([ 9, 12, 15])

## 1.10 ndarray - Unique

For 1-D ndarrays. returns the sorted unique values in an array  



In [0]:
data_ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])


In [0]:
a = np.unique(data_ints) 				# Output: array([1, 2, 3, 4])


# 2 Pandas

In [0]:
import pandas as pd

## 2.12 Pandas - Data Structures



1.   Series
2.   Data Frame



In [0]:
ser = pd.Series([4, 5, 10, 3])


 execute in colab & spot difference from ndarray


In [114]:
ser 						


0     4
1     5
2    10
3     3
dtype: int64

## Q. 2.12.1 What difference did you observe?

In [115]:
ser.values


array([ 4,  5, 10,  3])

In [116]:
Ser.index


NameError: ignored

## Q. 2.12.2 Why the error?

## 2.13 Pandas - DataFrame


In [117]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'], 'year': [2000, 2001, 2002, 2001, 2002], 'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
data

{'pop': [1.5, 1.7, 3.6, 2.4, 2.9],
 'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002]}

In [119]:
df = pd.DataFrame(data)  
df

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

## 2.14 Indexing, Selection, Index dropping	



In [120]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [121]:
obj['b']  


1.0

In [122]:
obj[1]


1.0

### Dropping one or more entries from an axis  


In [123]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])


a    0.0
b    1.0
e    4.0
dtype: float64

In [127]:
obj.drop('c')


a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [125]:
obj.drop(['d', 'c'])


a    0.0
b    1.0
e    4.0
dtype: float64

## 2.15 Indexing, Selection, Index dropping -2	


Selection with loc & iloc
Select rows & columns using axis labels (loc) or integers (iloc).


In [0]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),index=['Ohio', 'Colorado', 'Utah', 'New York'], columns=['one', 'two', 'three', 'four'])  

data.iloc[2, [3, 0, 1]]


four    11
one      8
two      9
Name: Utah, dtype: int64

In [0]:
data.loc['Colorado', ['two', 'three']]


two      5
three    6
Name: Colorado, dtype: int64

In [0]:
data.iloc[2, [3, 0, 1]]


four    11
one      8
two      9
Name: Utah, dtype: int64

## 2.16 Pandas - Descriptive Statistics


In [0]:
df = DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]], index=['a', 'b', 'c', 'd'], columns=['one', 'two'])  


NameError: ignored

## Q 2.16. Why the error?

In [130]:
df.sum()  


state    OhioOhioOhioNevadaNevada
year                        10006
pop                          12.1
dtype: object

In [128]:
df.head()


state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [129]:
df.tail()


state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9