<a href="https://colab.research.google.com/github/arbi11/YCBS-272/blob/master/Lec_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
data = np.random.randn(2, 3)

In [4]:
data

array([[-1.6297486 , -0.44564401,  0.16087996],
       [-0.12795706, -0.49847062, -1.11264871]])

perform mathematical operations on whole blocks of data

In [5]:
data*2

array([[-3.2594972 , -0.89128802,  0.32175992],
       [-0.25591412, -0.99694125, -2.22529742]])

Q. Create a 2 by 4 array of samples from with mean of 3

In [6]:
data+data

array([[-3.2594972 , -0.89128802,  0.32175992],
       [-0.25591412, -0.99694125, -2.22529742]])

In [7]:
data.shape

(2, 3)

In [8]:
data.dtype

dtype('float64')

In [0]:
arr = np.array([1, 2, 3, 4, 5])

In [10]:
arr.dtype

dtype('int64')

In [0]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1], dtype= np.float32)

In [18]:
arr.dtype

dtype('float32')

integers were cast to floating point. If I cast some floating point numbers to be of integer dtype, the decimal part will be truncated

In [0]:
arr2 = arr.astype(np.int32)

In [0]:
arr3 = arr2.astype(float)

In [21]:
arr3.dtype

dtype('float64')