<a href="https://colab.research.google.com/github/arbi11/YCBS-272/blob/master/Lec_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Import the necessary libraries

In [0]:
import numpy as np

## 1.1 Creating a numpy array

In [0]:
data = np.random.rand(2, 4)

the array can be printed with just mentioning the variable name

In [5]:
data

array([[0.97884115, 0.1622496 , 0.41781171, 0.71349695],
       [0.88407781, 0.5070871 , 0.74571205, 0.67995647]])

## Q1. Create a variable with size [3, 6]

## 1.2 Creating a numpy array from sampling via normal distribution
creating an array with random numbers from normal distribution

N(mu, sd)


numpy samples from N(mu, variance) of N(0, 1)

In [7]:
data = np.random.randn(2, 4)
data

array([[ 0.50342014,  1.28165121,  1.20886991,  0.22903815],
       [ 0.22199126,  0.95831356, -1.79270578,  0.6123828 ]])

## Q2. Create a variable with normal data size [2, 4] with mu = 5 and sd = 2
variance = ?

## 1.3 Data shape

In [8]:
data.shape


(2, 4)

## 1.4 Data type

In [9]:
data.dtype 


dtype('float64')

In [0]:
arr = np.array([1, 2, 3, 4, 5])

In [0]:
arr.dtype

In [0]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1], dtype= np.float32)

In [0]:
arr.dtype

### 1.4.1 integers were cast to floating point. If I cast some floating point numbers to be of integer dtype, the decimal part will be truncated

In [0]:
arr2 = arr.astype(np.int32)

In [0]:
arr3 = arr2.astype(float)

In [0]:
arr3.dtype

## 1.5 Perform mathematical operations on whole blocks of data

In [0]:
data*2

array([[-3.2594972 , -0.89128802,  0.32175992],
       [-0.25591412, -0.99694125, -2.22529742]])

In [0]:
data+data

array([[-3.2594972 , -0.89128802,  0.32175992],
       [-0.25591412, -0.99694125, -2.22529742]])

In [10]:
1/data

array([[ 1.98641239,  0.78024348,  0.82721887,  4.36608483],
       [ 4.50468188,  1.04349979, -0.55781602,  1.63296553]])

In [0]:
data.shape

(2, 3)

In [59]:
data.dtype

dtype('int64')

## Q3. How to provide a copy of the data rather than just a view

integers were cast to floating point. If I cast some floating point numbers to be of integer dtype, the decimal part will be truncated

## 1.6 Indexing & Slicing - 1D

In [0]:
data = np.arange(10)
	

select the element at 6th index. Remember first index starts is at 0.

Q. Select the first element

select from 5th to 7th element. Stop index not included.

In [57]:
data[5:8]	


array([], shape=(0, 5), dtype=int64)

Indexing & assignment

In [0]:
data[5:8] = 6
data[:] = 0 

## 1.8 Ndarray - Indexing & Slicing - Higher dimension


In [0]:
data_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


selects the 3rd row

In [13]:
data_2d[2] 			


array([7, 8, 9])

 select elements with <row, column> indexing format

In [14]:
data_2d[0][2]		


3

What will this do?

In [15]:
data_2d[0, 2] 		

3

Another way for indexing

Slicing: select range of elements


In [54]:
data_2d[:2] 		# slicing along axis 0 (row): select everything above row#3
data_2d[1, :2]		# practice in colab


array([3, 4])

## 1.8 ndarray - Transposing & Swapping Axes

In [0]:
data = np.arange(15).reshape((3, 5))  


In [52]:
data.shape 					# check in colab
data.T 						# transpose of the original ndarray

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

For high dimension


In [53]:
data_3d = np.arange(16).reshape((2, 2, 4))  # accepts a tuple of axis
data_3d.transpose((1, 0, 2))  


array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

Q. Are you creating a copy or view?

Q. Check what .T will do on high dimensional data?

Q. Try data_3d.swapaxes(1,2)


## 1.9 ndarray - Statistical methods


In [0]:
data = np.random.randn(5, 4) 		# normally-distributed data  


In [16]:
data.mean() 					
np.mean(data) 				


4.5

For high dimension data
data_2d = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])  
data_2d.mean(axis=1) 				# mean over the given axis  
data_2d.sum(0) 		

In [17]:
data_2d = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])  
data_2d.mean(axis=1) 				# mean over the given axis  
data_2d.sum(0) 		

array([ 9, 12, 15])

## 1.10 ndarray - Unique

For 1-D ndarrays. returns the sorted unique values in an array  



In [0]:
data_ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])


In [19]:
np.unique(data_ints) 				# Output: array([1, 2, 3, 4])


array([1, 2, 3, 4])

# 2 Pandas

In [0]:
import pandas as pd

## 2.12 Pandas - Data Structures



1.   Series
2.   Data Frame



In [0]:
ser = pd.Series([4, 5, 10, 3])


 execute in colab & spot difference from ndarray


In [26]:
ser 						


0     4
1     5
2    10
3     3
dtype: int64

Q. What difference did you observe?

In [27]:
ser.values


array([ 4,  5, 10,  3])

In [30]:
Ser.index


NameError: ignored

Q. Why the error?

## 2.13 Pandas - DataFrame


In [0]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'], 'year': [2000, 2001, 2002, 2001, 2002], 'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}


In [0]:
df = pd.DataFrame(data)  


## 2.14 Indexing, Selection, Index dropping	



In [0]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])


In [37]:
obj['b']  


1.0

In [39]:
obj[1]


1.0

### Dropping one or more entries from an axis  


In [42]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
new_obj =  obj.drop('c')
obj.drop(['d', 'c'])


a    0.0
b    1.0
e    4.0
dtype: float64

## 2.15 Indexing, Selection, Index dropping -2	


Selection with loc & iloc
Select rows & columns using axis labels (loc) or integers (iloc).


In [43]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),index=['Ohio', 'Colorado', 'Utah', 'New York'], columns=['one', 'two', 'three', 'four'])  

data.iloc[2, [3, 0, 1]]


four    11
one      8
two      9
Name: Utah, dtype: int64

In [45]:
data.loc['Colorado', ['two', 'three']]


two      5
three    6
Name: Colorado, dtype: int64

In [44]:
data.iloc[2, [3, 0, 1]]


four    11
one      8
two      9
Name: Utah, dtype: int64

## 2.16 Pandas - Descriptive Statistics


In [50]:
df = DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]], index=['a', 'b', 'c', 'd'], columns=['one', 'two'])  


NameError: ignored

Q. Why the error?

In [49]:
df.sum()  
df.head()
df.tail()


one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3